Web UI code separation and improvements
decred/hardforkdemo pull request #62
Opened 2017-04-01 04:42 UTC by chappjc

This PR is intended to go in **after** PR https://github.com/decred/hardforkdemo/pull/61.  I will rebase this when PR https://github.com/decred/hardforkdemo/pull/61 is merged.

The correct comparison: https://github.com/decred/hardforkdemo/compare/pull/61/head...chappjc:webui-type

This PR adds:

- web.go, containing a web ui type and it's associated functions.
- reloadsig.go and reloadsig_windows to allow reparsing templates on SIGUSR1, which allows templates to be reloaded without restarting the whole app.
- A LICENSE file (ISC).

The cli flags commit is part of the other PR.

2017-04-01 04:44 UTC, chappjc commented
@karamble I need this and PR https://github.com/decred/hardforkdemo/pull/61 to go in before I add both the stubbed client (fake JSON data) and the data storage system.  However, I don't have an easy way to test since the agendas are gone from testnet2.  Can this be tried on the testnet1 machine?

2017-04-01 04:46 UTC, chappjc commented
@alexlyp Do you guys have a way to run a simnet voting scenario? hardforkdemo could latch on to that, if it exists.

2017-04-01 05:01 UTC, chappjc commented
Alternatively I can instead PR into a devel branch until we're able to work out a simple testing method.  I'd like to get moving on the next steps, particularly the JSON client stub, but I don't want to pile PR on top of PR.

Or we can move forward with the understanding that this might not work as intended yet, but that will change when we've got a fake data input.

2017-04-01 05:10 UTC, karamble commented
i expect a relaunch of the complete frontend as it currently got redesigned from scratch by the branding team, read more about it in the #hardforkwebsite slack room ...

2017-04-18 15:31 UTC, alexlyp requested changes
Looks good, just need that license fix and that #61 fix

2017-04-18 15:31 UTC, alexlyp commented on LICENSE
> +Copyright (c) 2014-2016, The btcsuite developers
You can remove btcsuite devs from this repo.

2017-04-18 21:54 UTC, alexlyp approved these changes

2017-04-18 21:54 UTC, merged